package pro.fazeclan.river.stupid_express.role.amnesiac;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.entity.PlayerBodyEntity;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.network.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionResult;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import pro.fazeclan.river.stupid_express.constants.SERoles;
public class RoleSelectionHandler {

    public static void init() {
        UseEntityCallback.EVENT.register(((player, level, interactionHand, entity, entityHitResult) -> {
            if (!(player instanceof ServerPlayer interacting)) {
                return InteractionResult.PASS;
            }
            if (!interacting.gameMode.isSurvival()) {
                return InteractionResult.PASS;
            }
            GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(player.level());
            if (!gameWorldComponent.isRole(player, SERoles.AMNESIAC)) {
                return InteractionResult.PASS;
            }
            if (!(entity instanceof PlayerBodyEntity victim)) {
                return InteractionResult.PASS;
            }
            Role role = gameWorldComponent.getRole(victim.getPlayerUuid());

            PlayerShopComponent playerShopComponent = PlayerShopComponent.KEY.get(player);

            gameWorldComponent.addRole(player, role);
            ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, role);
            playerShopComponent.setBalance(200);
            if (Harpymodloader.VANNILA_ROLES.contains(role)) {
                if (role.equals(WatheRoles.VIGILANTE)) {
                    player.addItem(WatheItems.REVOLVER.getDefaultInstance());
                }
                ServerPlayNetworking.send(
                        interacting,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(
                                        role.equals(WatheRoles.VIGILANTE) ? RoleAnnouncementTexts.VIGILANTE :
                                                role.equals(WatheRoles.KILLER) ? RoleAnnouncementTexts.KILLER :
                                        RoleAnnouncementTexts.CIVILIAN),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            } else {
                ServerPlayNetworking.send(
                        interacting,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role)),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            }

            return InteractionResult.CONSUME;
        }));
    }

}