package pro.fazeclan.river.stupid_express.mixin.role.initiate;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.network.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import pro.fazeclan.river.stupid_express.StupidExpress;
import pro.fazeclan.river.stupid_express.constants.SERoles;

import java.util.ArrayList;
import java.util.Collections;

@Mixin(GameFunctions.class)
public abstract class InitiateKillMixin {

    @Inject(
            method = "killPlayer(Lnet/minecraft/world/entity/player/Player;ZLnet/minecraft/world/entity/player/Player;Lnet/minecraft/resources/ResourceLocation;)V",
            at = @At("HEAD")
    )
    private static void initiateKill(Player victim, boolean spawnBody, Player killer, ResourceLocation deathReason, CallbackInfo ci) {
        if (!(victim instanceof ServerPlayer)) {
            return;
        }

        var level = (ServerLevel) victim.level();
        var gameWorldComponent = GameWorldComponent.KEY.get(level);

        if (!gameWorldComponent.isRole(victim, SERoles.INITIATE)) {
            return;
        }
        if (killer != null && gameWorldComponent.isRole(killer, SERoles.INITIATE)) {
            killer.getInventory().removeItem(WatheItems.KNIFE.getDefaultInstance());
            var shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
            shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
            if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(WatheRoles.KILLER);
            Collections.shuffle(shuffledKillerRoles);

            var role = shuffledKillerRoles.getFirst();
            gameWorldComponent.addRole(killer, role);
            ModdedRoleAssigned.EVENT.invoker().assignModdedRole(killer, role);
            if (Harpymodloader.VANNILA_ROLES.contains(role)) {
                ServerPlayNetworking.send((ServerPlayer) killer, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(RoleAnnouncementTexts.KILLER), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
            } else {
                ServerPlayNetworking.send((ServerPlayer) killer, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role)), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
            }
        }
    }

    @Inject(
            method = "killPlayer(Lnet/minecraft/world/entity/player/Player;ZLnet/minecraft/world/entity/player/Player;Lnet/minecraft/resources/ResourceLocation;)V",
            at = @At("HEAD"),
            cancellable = true
    )
    private static void initiateKillNonInitiate(
            Player victim,
            boolean spawnBody,
            Player killer,
            ResourceLocation deathReason,
            CallbackInfo ci
    ) {
        if (!(victim instanceof ServerPlayer)) {
            return;
        }

        var level = (ServerLevel) victim.level();
        var gameWorldComponent = GameWorldComponent.KEY.get(level);
        if (!gameWorldComponent.isRole(victim, SERoles.INITIATE) && killer != null && gameWorldComponent.isRole(killer, SERoles.INITIATE)) {
            Role newInitiateRole;
            switch (StupidExpress.CONFIG.rolesSection.initiateSection.initiateFallbackRole) {
                case KILLER -> {
                    var shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
                    shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
                    if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(WatheRoles.KILLER);
                    Collections.shuffle(shuffledKillerRoles);

                    newInitiateRole = shuffledKillerRoles.getFirst();
                }
                case NEUTRAL -> {
                    var shuffledNeutralRoles = new ArrayList<>(WatheRoles.ROLES);
                    shuffledNeutralRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || role.canUseKiller() || role.isInnocent() || role.equals(SERoles.AMNESIAC) || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
                    if (shuffledNeutralRoles.isEmpty()) shuffledNeutralRoles.add(SERoles.AMNESIAC);
                    Collections.shuffle(shuffledNeutralRoles);

                    newInitiateRole = shuffledNeutralRoles.getFirst();
                }
                case null, default -> newInitiateRole = SERoles.AMNESIAC;
            }
            for (ServerPlayer player : level.getPlayers(p -> gameWorldComponent.isRole(p, SERoles.INITIATE))) {
                player.getInventory().removeItem(WatheItems.KNIFE.getDefaultInstance());
                gameWorldComponent.addRole(player, newInitiateRole);
                ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, newInitiateRole);
                if (Harpymodloader.VANNILA_ROLES.contains(newInitiateRole)) {
                    ServerPlayNetworking.send(player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(RoleAnnouncementTexts.KILLER), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
                } else {
                    ServerPlayNetworking.send(player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(newInitiateRole)), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
                }
            }
            if (!spawnBody) {
                victim.teleportTo(killer.getX(), killer.getY(), killer.getZ());
                victim.fallDistance = 0.0f;
            }
            GameFunctions.killPlayer(killer, true, null, StupidExpress.id("failed_initiation"));
            ci.cancel();
        } else if (gameWorldComponent.isRole(victim, SERoles.INITIATE) && killer != null && !gameWorldComponent.isRole(killer, SERoles.INITIATE)) {
            Role newInitiateRole;
            switch (StupidExpress.CONFIG.rolesSection.initiateSection.initiateFallbackRole) {
                case KILLER -> {
                    var shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
                    shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
                    if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(WatheRoles.KILLER);
                    Collections.shuffle(shuffledKillerRoles);

                    newInitiateRole = shuffledKillerRoles.getFirst();
                }
                case NEUTRAL -> {
                    var shuffledNeutralRoles = new ArrayList<>(WatheRoles.ROLES);
                    shuffledNeutralRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || role.canUseKiller() || role.isInnocent() || role.equals(SERoles.AMNESIAC) || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
                    if (shuffledNeutralRoles.isEmpty()) shuffledNeutralRoles.add(SERoles.AMNESIAC);
                    Collections.shuffle(shuffledNeutralRoles);

                    newInitiateRole = shuffledNeutralRoles.getFirst();
                }
                case null, default -> newInitiateRole = SERoles.AMNESIAC;
            }
            for (ServerPlayer player : level.getPlayers(p -> gameWorldComponent.isRole(p, SERoles.INITIATE))) {
                player.getInventory().removeItem(WatheItems.KNIFE.getDefaultInstance());
                gameWorldComponent.addRole(player, newInitiateRole);
                ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, newInitiateRole);
                if (Harpymodloader.VANNILA_ROLES.contains(newInitiateRole)) {
                    ServerPlayNetworking.send(player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(RoleAnnouncementTexts.KILLER), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
                } else {
                    ServerPlayNetworking.send(player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(newInitiateRole)), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
                }
            }
        }
    }

}
