package pro.fazeclan.river.stupid_express.role.necromancer;

import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.compat.TrainVoicePlugin;
import dev.doctor4t.wathe.entity.PlayerBodyEntity;
import dev.doctor4t.wathe.network.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.GameType;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import pro.fazeclan.river.stupid_express.cca.AbilityCooldownComponent;
import pro.fazeclan.river.stupid_express.constants.SERoles;
import pro.fazeclan.river.stupid_express.role.necromancer.cca.NecromancerComponent;

import java.util.ArrayList;
import java.util.Collections;

public class RevivalSelectionHandler {

    public static void init() {
        UseEntityCallback.EVENT.register(((player, level, interactionHand, entity, entityHitResult) -> {
            if (!(player instanceof ServerPlayer interacting)) {
                return InteractionResult.PASS;
            }
            if (!interacting.gameMode.isSurvival()) {
                return InteractionResult.PASS;
            }
            GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(player.level());
            if (!gameWorldComponent.isRole(player, SERoles.NECROMANCER)) {
                return InteractionResult.PASS;
            }
            if (!(entity instanceof PlayerBodyEntity body)) {
                return InteractionResult.PASS;
            }

            var serverLevel = (ServerLevel) level;

            // check if the selected body can be revived
            var revived = (ServerPlayer) serverLevel.getPlayerByUUID(body.getPlayerUuid());
            if (revived == null) {
                return InteractionResult.PASS;
            }
            var nc = NecromancerComponent.KEY.get(serverLevel);
            if (nc.getAvailableRevives() < 1) {
                return InteractionResult.PASS;
            }

            // activate cooldown
            AbilityCooldownComponent cooldown = AbilityCooldownComponent.KEY.get(player);
            if (cooldown.hasCooldown()) {
                return InteractionResult.PASS;
            }
            cooldown.setCooldown(3 * 60 * 20);
            nc.decreaseAvailableRevives();
            nc.sync();

            // get random killer role
            var roles = new ArrayList<>(WatheRoles.ROLES);
            roles.remove(SERoles.NECROMANCER);
            roles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role)
                    || !role.canUseKiller()
                    || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString()));
            if (roles.isEmpty()) roles.add(WatheRoles.KILLER);
            Collections.shuffle(roles);

            // revive player and give them the role
            var selectedRole = roles.getFirst();

            revived.teleportTo(body.getX(), body.getY(), body.getZ());
            revived.setGameMode(GameType.ADVENTURE);
            body.remove(Entity.RemovalReason.DISCARDED); // like it never existed

            gameWorldComponent.addRole(revived, selectedRole);

            PlayerShopComponent playerShopComponent = PlayerShopComponent.KEY.get(revived);
            playerShopComponent.setBalance(200);

            TrainVoicePlugin.resetPlayer(revived.getUUID()); // remove the revived from the spectator group

            if (Harpymodloader.VANNILA_ROLES.contains(selectedRole)) {
                ServerPlayNetworking.send(
                        revived,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(RoleAnnouncementTexts.KILLER),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            } else {
                ServerPlayNetworking.send(
                        revived,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(selectedRole)),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            }
            TrainVoicePlugin.resetPlayer(revived.getUUID());

            return InteractionResult.CONSUME;
        }));
    }

}
